version: "3.7"

services:
    app:
        build:
            args:
                user: developer
                uid: 1000
            context: ./
            dockerfile: docker/Dockerfile
        env_file:
            - .env
        image: app
        container_name: app-crypto-news
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: crypto-news.test
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ~/.ssh:/root/.ssh
        depends_on:
            - db
            - redis
        networks:
            - laravel
    db:
        image: mysql:8.0
        container_name: mysql-crypto-news
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/logs:/var/log/mysql
            - ./docker/mysql/ql:/docker-entrypoint-initdb.d
        networks:
            - laravel
    nginx:
        image: nginx:alpine
        container_name: nginx-crypto-news
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/nginx/ssl:/etc/nginx/conf.d/ssl
            - ./docker/nginx/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
        networks:
            - laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin-crypto-news
        ports:
            - 8080:80
        links:
            - db
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        networks:
            - laravel
    redis:
        image: "redis:alpine"
        container_name: redis-crypto-news
        restart: unless-stopped
        volumes:
            - ./docker/redis/data:/data
        ports:
            - "6379:6379"
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
